<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 14,
                'name' => 'Lopez Roland Shane',
                'email' => 'lopezrolandshane@gmail.com',
                'username' => 'shaner',
                'password' => Hash::make('password'),
                'phone' => '12314134',
                'fb_id' => 0,
                'google_id' => '107236937285983559710',
                'profile_picture' => 'profile-pictures/NsqtYbR4bm9qTg7FvyIID8MApPz7MhofeBfoJ5WS.jpg',
                'address' => 'dsadsadad',
                'active_status' => 0,
                'verify_status' => 0,
                'role' => 'admin',
                'strike' => 3,
                'email_verification_code' => 796437,
                'email_verified_at' => '2024-11-07 04:19:18',
                'created_at' => '2024-08-11 19:56:43',
                'updated_at' => '2024-11-15 06:09:28',
            ],
            [
                'id' => 68,
                'name' => 'Roland Shane Lopez',
                'email' => 'rshan0418@gmail.com',
                'username' => 'roland',
                'password' => Hash::make('password'),
                'phone' => '09661805821',
                'fb_id' => null,
                'google_id' => null,
                'profile_picture' => 'profile_picture/kEDKEjA3jRNNPztmQNrveSXYF.jpg',
                'address' => 'purok 3 tres de mayo',
                'active_status' => 0,
                'verify_status' => 1,
                'role' => 'owner',
                'strike' => 3,
                'email_verification_code' => null,
                'email_verified_at' => '2024-11-21 02:16:40',
                'created_at' => '2024-11-20 18:15:59',
                'updated_at' => '2024-11-20 20:32:21',
            ],
            [
                'id' => 69,
                'name' => 'Roland Shane Lopez',
                'email' => 'rshan5418@gmail.com',
                'username' => null,
                'password' => null,
                'phone' => '090909090909',
                'fb_id' => 1071441051576088,
                'google_id' => null,
                'profile_picture' => 'profile_picture/17P7uknT1nLNN3tJZEDWeodhu.jpg',
                'address' => 'purok 3 tres de mayo',
                'active_status' => 0,
                'verify_status' => 0,
                'role' => 'tenant',
                'strike' => 2,
                'note' => 'Your review contains inappropriate words.',
                'email_verification_code' => null,
                'email_verified_at' => '2024-11-21 02:24:38',
                'created_at' => '2024-11-20 18:23:38',
                'updated_at' => '2024-11-22 19:40:26',
            ],
            [
                'id' => 70,
                'name' => 'Degam Jhonry',
                'email' => 'jhonrydegamo@gmail.com',
                'username' => 'degads',
                'password' => Hash::make('password'),
                'phone' => '09090909090',
                'fb_id' => null,
                'google_id' => null,
                'profile_picture' => 'profile_picture/FurI715A5UrGqPiKsbWG1svii.jpg',
                'address' => 'purok 3 tres de mayo',
                'active_status' => 0,
                'verify_status' => 1,
                'role' => 'owner',
                'strike' => 3,
                'note' => null,
                'email_verification_code' => null,
                'email_verified_at' => '2024-11-21 03:35:42',
                'created_at' => '2024-11-20 19:34:52',
                'updated_at' => '2024-11-20 19:35:49',
            ],
            [
                'id' => 71,
                'name' => 'shane lopez',
                'email' => 'nokielopez@gmail.com',
                'username' => null,
                'password' => null,
                'phone' => '090909090909',
                'fb_id' => null,
                'google_id' => '106648757521862198329',
                'profile_picture' => 'profile_picture/A53NKFOPfoZAZxDuuTlWf5sZc.jpg',
                'address' => 'Tres De Mayo',
                'active_status' => 0,
                'verify_status' => 0,
                'role' => 'tenant',
                'strike' => 3,
                'note' => null,
                'email_verification_code' => null,
                'email_verified_at' => '2024-11-21 04:32:53',
                'created_at' => '2024-11-20 20:32:53',
                'updated_at' => '2024-11-20 20:33:15',
            ],
        ]);
    }
}